version: "3.9"

services:
  web:
    build: .
    image : django
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # copy the sql script to create tables
      #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # fill the tables
      #- ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  migration:
    image: django
    command: python /code/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  postgres_data: