version: "3.9"

services:
  web:
    build: .
    image : django
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres  
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: postgres  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - dda-network
  migration:
    image: django
    command: python /code/manage.py migrate --noinput
    volumes:
      - .:/code
    networks:
      - dda-network
    depends_on:
      - db
networks:
  dda-network:
    name: dda-network
volumes:
  postgres_data:
