name: Django Devops CI/CD Pipeline

on:
  push:
    branches: [ "master" ]


    
jobs:

  build_test_push:
    runs-on: ubuntu-latest
    #services:
      #postgres:
        #image: postgres:13
        #env:
          #POSTGRES_DB: postgres
          #POSTGRES_USER: postgres
          #POSTGRES_PASSWORD: postgres
          
          
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt 

    - name: Login to DockerHub  
      uses: docker/login-action@v1
      with:
          username: ${{secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
          
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag baldita/devops-django-app:${{ github.sha }}

    - name: Build Compose
      run: docker-compose up -d 

    - name: Wait for PostgreSQL to be ready
      run: |
          until docker-compose -f docker-compose.yml exec -T db pg_isready; do
            sleep 2
          done

    - name: Run the tests
      env:
        DJANGO_SETTINGS_MODULE: devopsPproject.settings
      run: python manage.py test --keepdb --verbosity 2

    - name: Push Docker image to Docker Hub
      run: docker push baldita/devops-django-app:${{ github.sha }}
